dist: xenial
language: python
sudo: required
python:
  - "3.6.6"
  - "3.7.0"
cache: pip
install:
  - pip install -U --process-dependency-links --no-cache-dir --force-reinstall red-discordbot[mongo]
  - pip install -r requirements.txt
script:
  - python -m compileall .
  - black --check -l 99 -N `git ls-files "*.py"`
notifications:
  email: false
