dist: trusty
sudo: false
language: python

python:
  - 3.6.5

install:
 - pip install -U --process-dependency-links --no-cache-dir red-discordbot
 - pip install black

script:
  - python -m compileall .
  - black --check `git ls-files "*.py"`