dist: trusty
sudo: false
language: python

python:
  - 3.6.5

install:
 - pip install -r requirements.txt

script:
  - python -m compileall .
  - black --check `git ls-files "*.py"`

notifications:
  email: false